/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static void delay_ms(volatile uint32_t ms) {
  while (ms--) {
    for (volatile uint32_t i = 0; i < 40000; ++i) { __asm__("nop"); }
  }
}

int main(void)
{
  // RCC base address (from the memory map chapter). Note: end all hex address defines with UL (unsigned long)
  #define RCC_BASE  0x40023800UL

  // AHB1ENR is at offset 0x30. GPIOA/D lives here
  #define RCC_AHB1ENR  (*(volatile unsigned int *)(RCC_BASE + 0x30))
  // APB1ENR is at offset 0x40. UART2 lives here.
  #define RCC_APB1ENR (*(volatile unsigned int *)(RCC_BASE + 0x40))

  // Set bit 0 in AHB1 bus to enable GPIOA clock. Note: this enables clock for PA0 - PA15
  RCC_AHB1ENR |= (1 << 0);
  volatile unsigned int tmp = RCC_AHB1ENR; (void) tmp; // void tmp tells compiler to ignore unused var
  // Set bit 3 in AHB1 bus to enable GPIOD clock. Note: this enables clock for PD0 - PD15
  RCC_AHB1ENR |= (1 << 3);
  // Readback after clock enable (force CPU to wait for write to complete)
  volatile unsigned int tmp = RCC_AHB1ENR; (void) tmp; // void tmp tells compiler to ignore unused var
  // set bit 17 in the APB1 bus to enable USART2 clock
  RCC_APB1ENR |= (1 << 17);

  // GPIOA base address. PA2 and PA3 (for UART comms) live here.
  #define GPIOA_BASE 0x40020000UL
  // USART2 base address
  #define USART2_BASE 0x40004400UL

  // GPIOD base address (from memory map). LEDs live here. UL = unsigned long, compiler treats it as 32-bit value rather than signed integer
  #define GPIOD_BASE  0x40020C00UL

  // GPIOD_MODER is the first register in GPIOD
  #define GPIOD_MODER (*(volatile unsigned int *)(GPIOD_BASE + 0x00))

  // set bit 24 to configure pin 12 (green LED) of GPIOD to "general purpose output mode"
  GPIOD_MODER |= (1 << 24);
  // also set bit 26 to configure pin 13 (<> LED) of GPIOD to "g/p output mode"
  GPIOD_MODER |= (1 << 26);
  //also set bit 28 to configure pin 14 (<> LED) of GPIOD to "g/p output mode"
  GPIOD_MODER |= (1 << 28);
  // also set bit 30 to configure pin 15 (blue LED) of GPIOD to "g/p output mode"
  GPIOD_MODER |= (1 << 30);

  // GPIOD_ODR (output data register) is at offset 0x14
  #define GPIOD_ODR (*(volatile unsigned int *)(GPIOD_BASE + 0x14))

  // GPIOD_BSRR (bit set/reset register) is at offset 0x18
  #define GPIOD_BSRR (*(volatile unsigned int *)(GPIOD_BASE + 0x18))
  
  // create LED bitmask array
  const uint32_t leds[] = { (1U << 12), (1U << 13), (1U << 14), (1U << 15) };
  
  // Loop forever
	while(1) {
    for (int i = 0; i < 4; ++i) {
        // reset all four pins (write 1s to upper half of BSRR to reset)
        GPIOD_BSRR = (leds[0] << 16) | (leds[1] << 16) | (leds[2] << 16) | (leds[3] << 16);
        // set only the 'chosen' LED
        GPIOD_BSRR = leds[i];
        delay_ms(20);
    }
  }
}
